---

apiVersion: v1
kind: Service
metadata:
  name: "service-2048"
  namespace: az-keyvault-demo
  labels:
    app: "2048"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "2048"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
  namespace: az-keyvault-demo
  labels:
    aadpodidbinding: pod-id-binding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "2048"
  template:
    metadata:
      labels:
        app: "2048"
        aadpodidbinding: pod-id-binding
        version: v1
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: "2048"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "secret-provider-kv"